project:
  type: website
  output-dir: docs
  resources:
    - index.html
    - about.html
    - posts.html
    - nyt.html
    - image_assets/**
    - Dollman_CV.pdf

website:
  title: "Justin Dollman"
  navbar: false

format:
  html:
    theme: theme-minimal.scss
    include-before-body: _includes/back-link.html
    grid:
      margin-width: 350px

editor: source

