project:
  type: website
  output-dir: docs
website:
  title: "Justin Dollman"
  navbar:
    right:
      - section_dissertation.qmd
      - section_assorted.qmd
      - section_about.qmd
format:
  html:
    theme: zephyr
    css: styles.css

editor: source

