---
title: "About Me"
---

Since this site's *raison d'être* is professional, I should say a word or two about me *qua* wage laborer. 

I'm a PhD candidate in political science at SUNY Stony Brook where I'm working on my dissertation under the guidance of [Michael Peress](http://www.michaelperess.com/). During my time here I've had the pleasure of taking courses with such luminaries as [Stanley Feldman](https://en.wikipedia.org/wiki/Stanley_Feldman_(political_scientist)), [Andy Delton](https://sites.google.com/site/andrewdeltonpubs/), [Yanna Krupnikov](https://en.wikipedia.org/wiki/Yanna_Krupnikov), and [Vittorio Mérola](http://vittoriomerola.com/). The dissertation I'm currently wrapping up current consists of three mostly independent chapters, covering immigration opinion's effect on immigration policymaking at the level of US states, cross-national comparisons of the urban-rural divide across the globe, and an intranational study of urban-rural movements and ideological shifts in the Netherlands. These topics represent my _circa_ 2019 interests preserved in amber, with my current interests having moved onto descriptive political epistemology and understanding the interaction between public opinion and legislative institutions regarding artificial intelligence lawmaking.

At Stony Brook I've been the 'instructor of record' for Introduction to Statistics (undergraduate and graduate) and Experiments in Political Science (undergraduate). In addition to those bureaucratically sanctioned courses, I also taught an Introductory Math Camp to incoming PhD students and, along with my esteemed former colleague [Pei-Hsun Hsieh](https://phsieh.com/), I co-taught a weekly introduction to `R` during the Fall 2019 semester to graduate students from sundry social sciences (the infamous [flyer](seven-ds.pdf)). Simultaneously with the courses here at Stony Brook, I've been teaching statistics and data analysis to students from other graduate programs as well as MBA students.

Before landing on the Ye Longe Isle of Bagels & Hockey Fanatics, I taught English for a few years in Ecuador and Peru. And before that, I triple majored in philosophy, psychology, and German at the University of Arkansas (with a year spent at Karl-Franzens Universität in Graz, Austria).